"""回放/可视化一个 `.npz` 动作文件。

脚本会：
1) 启动 Isaac Sim；
2) 创建一个简单场景（地面 + 灯光 + G1-29DOF 机器人）；
3) 从 `.npz` 中读取离线录制的轨迹数据（关节与各刚体的世界系状态）；
4) 在仿真中把这些状态逐帧写回机器人，并循环播放；
5) 只渲染、不做物理步进（不 `sim.step()`），因此它主要用于“检查/调试导出的轨迹”。

用法示例（假设你的动作文件是由 `csv_to_npz.py` 生成的）：:

    python replay_npz.py -f path_to_motion.npz
"""

# 启动 Isaac Sim 应用（底层基于 Kit/Omniverse），后续才可以创建场景和仿真上下文。

import argparse
import numpy as np
import torch

from isaaclab.app import AppLauncher

# 添加命令行参数
parser = argparse.ArgumentParser(description="Replay converted motions.")
parser.add_argument(
    "--file",
    "-f",
    type=str,
    required=True,
    help="Path to motion npz file (generated by scripts/mimic/csv_to_npz.py).",
)

# 把 Isaac/Kit 的通用参数追加到 argparse（例如 headless、device 等）
AppLauncher.add_app_launcher_args(parser)

# 解析参数
args_cli = parser.parse_args()

# 启动 Omniverse / Isaac Sim 应用
app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

# 之后的 import 需要在应用启动后进行，否则在某些 Isaac Lab 环境里可能缺少运行时依赖。

import isaaclab.sim as sim_utils
from isaaclab.assets import Articulation, ArticulationCfg, AssetBaseCfg
from isaaclab.scene import InteractiveScene, InteractiveSceneCfg
from isaaclab.sim import SimulationContext
from isaaclab.utils import configclass
from isaaclab.utils.assets import ISAAC_NUCLEUS_DIR

from unitree_rl_lab.assets.robots.unitree import UNITREE_G1_29DOF_CFG as ROBOT_CFG  # Currently only support G1-29dof
from unitree_rl_lab.tasks.mimic.mdp import MotionLoader

##
# Pre-defined configs
##


@configclass
class ReplayMotionsSceneCfg(InteractiveSceneCfg):
    """回放场景配置：地面、灯光、以及一台用于回放的机器人。"""

    # 地面
    ground = AssetBaseCfg(prim_path="/World/defaultGroundPlane", spawn=sim_utils.GroundPlaneCfg())

    # 场景光照（穹顶光 + HDR 天空贴图）
    sky_light = AssetBaseCfg(
        prim_path="/World/skyLight",
        spawn=sim_utils.DomeLightCfg(
            intensity=750.0,
            texture_file=f"{ISAAC_NUCLEUS_DIR}/Materials/Textures/Skies/PolyHaven/kloofendal_43d_clear_puresky_4k.hdr",
        ),
    )

    # 关节化机器人（Articulation）：这里使用 Unitree G1 29DOF
    robot: ArticulationCfg = ROBOT_CFG.replace(prim_path="{ENV_REGEX_NS}/Robot")


def run_simulator(sim: sim_utils.SimulationContext, scene: InteractiveScene):
    """主回放循环：从 `.npz` 读取离线轨迹，并写回到 Isaac Lab 里的机器人状态。"""

    # 取出场景中的机器人对象
    robot: Articulation = scene["robot"]

    # `scene.update()` 需要一个 dt。这里取仿真上下文本身的物理步长（但我们不执行 sim.step()）。
    sim_dt = sim.get_physics_dt()

    # 从 motion npz 加载离线轨迹。
    # MotionLoader 会把 npz 中的 joint/body 数据转换成 torch tensor，并提供：
    # - joint_pos: (T, J)
    # - joint_vel: (T, J)
    # - body_pos_w / body_quat_w / body_lin_vel_w / body_ang_vel_w: (T, B, ...)
    #
    # body_indexes 指定我们关心哪些刚体。这里传 [0]，表示“用录制数据里的第 0 个 body 来驱动机器人的根”。
    motion = MotionLoader(
        args_cli.file,
        torch.tensor([0], dtype=torch.long, device=sim.device),
        sim.device,
    )

    # 当前播放到的离散时间索引（每个 env 一份；这里 num_envs=1）
    time_steps = torch.zeros(scene.num_envs, dtype=torch.long, device=sim.device)

    # 仿真/渲染循环：按帧推进 time_steps，然后把轨迹状态写回仿真。
    while simulation_app.is_running():
        # 播放到下一帧
        time_steps += 1

        # 到达轨迹末尾后复位，从 0 开始循环播放
        reset_ids = time_steps >= motion.time_step_total
        time_steps[reset_ids] = 0

        # 先取一个“默认 root state”（包含 pos/quat/lin_vel/ang_vel 的正确向量布局）
        # 再把其中的 pos/quat/vel 用 motion 数据覆盖。
        root_states = robot.data.default_root_state.clone()

        # 根状态来自录制数据的 body_pos_w/body_quat_w/... 的第 0 号 body。
        # - body_pos_w.shape 约为 (T, 1, 3)；取 [:, 0] 变为 (T, 3) 以便赋值。
        # - body_quat_w 同理取第 0 号 body 的四元数。
        # - 速度同理。
        #
        # 同时加上 scene.env_origins 的平移：多环境时每个 env 有不同原点。
        root_states[:, :3] = motion.body_pos_w[time_steps][:, 0] + scene.env_origins[:, None, :]
        root_states[:, 3:7] = motion.body_quat_w[time_steps][:, 0]
        root_states[:, 7:10] = motion.body_lin_vel_w[time_steps][:, 0]
        root_states[:, 10:] = motion.body_ang_vel_w[time_steps][:, 0]

        # 写回 root（基座）状态
        robot.write_root_state_to_sim(root_states)

        # 写回关节状态：关节位置/速度直接来自 npz 的 joint_pos/joint_vel
        robot.write_joint_state_to_sim(motion.joint_pos[time_steps], motion.joint_vel[time_steps])

        # 同步场景内部数据缓存（某些传感器/可视化会依赖 scene 的数据刷新）
        scene.write_data_to_sim()

        # 只渲染，不做物理积分（不执行 sim.step()）
        sim.render()
        scene.update(sim_dt)

        # 相机跟随根部位置，方便观察回放是否正常
        pos_lookat = root_states[0, :3].cpu().numpy()
        sim.set_camera_view(pos_lookat + np.array([2.0, 2.0, 0.5]), pos_lookat)


def main():
    """创建仿真上下文与场景，并启动回放循环。"""
    sim_cfg = sim_utils.SimulationCfg(device=args_cli.device)

    # `SimulationCfg.dt` 用于仿真/scene 更新；此脚本不依赖物理积分，
    # 因而 dt 主要影响 scene.update() 内部刷新频率和时间相关逻辑。
    sim_cfg.dt = 0.02
    sim = SimulationContext(sim_cfg)

    # 单环境回放；env_spacing 只影响环境原点的布局
    scene_cfg = ReplayMotionsSceneCfg(num_envs=1, env_spacing=2.0)
    scene = InteractiveScene(scene_cfg)
    sim.reset()

    # 进入回放循环
    run_simulator(sim, scene)


if __name__ == "__main__":
    # run the main function
    main()
    # close sim app
    simulation_app.close()
